model_list:
  - model_name: openai/gpt-oss-20b
    litellm_params:
      model: nvidia_nim/openai/gpt-oss-20b
      api_key: os.environ/NVIDIA_API_KEY
      api_base: https://integrate.api.nvidia.com/v1

litellm_settings:
  drop_params: true