[PHP]
extension_dir = "C:\Users\spxph4227\scoop\apps\php\current\ext"
extension = curl
extension = fileinfo
extension = mbstring
extension = openssl
extension = pdo_pgsql
extension = pgsql
extension = sodium
extension = zip

date.timezone = Asia/Manila
memory_limit = 256M
max_execution_time = 120
display_errors = On
error_reporting = E_ALL
